#!/usr/bin/env bash
step_summary() {
    step "Summary — review before applying"

    printf '\n'
    printf '  Validator\n'
    printf '    name              : %s\n' "$SXT_LOCAL_VALIDATOR"
    printf '    SXT node metrics  : %s\n' "$SXT_PROMETHEUS_TARGET"
    printf '    node_exporter     : %s\n' "$NODE_EXPORTER_TARGET"
    printf '    data mountpoint   : %s\n' "$SXT_DATA_MOUNTPOINT"
    printf '\n'
    printf '  Host ports\n'
    printf '    Grafana           : %s (bind %s)\n' "$GRAFANA_PORT" "$GRAFANA_BIND"
    printf '    Prometheus        : %s\n' "$PROMETHEUS_PORT"
    printf '    ClickHouse HTTP   : %s\n' "$CLICKHOUSE_HTTP_PORT"
    printf '    ClickHouse native : %s\n' "$CLICKHOUSE_NATIVE_PORT"
    printf '    Exporter          : %s\n' "$SXT_EXPORTER_PORT"
    printf '\n'
    printf '  Credentials (masked)\n'
    printf '    Grafana admin     : %s / %s\n' \
        "${GRAFANA_ADMIN_USER:-admin}" "$(mask_password "$GRAFANA_ADMIN_PASSWORD")"
    printf '    CH exporter       : sxt_exporter / %s\n' "$(mask_password "$CLICKHOUSE_PASSWORD")"
    printf '    CH dashboard (RO) : sxt_dashboard / %s\n' "$(mask_password "$SXT_DASHBOARD_PASSWORD")"
    printf '\n'

    if ! ask_yn "Write .env and continue?" "y"; then
        error "Aborted by user."
        return 1
    fi

    write_env_file || return 1
    ok ".env written (mode 600)."
    return 0
}

write_env_file() {
    local tmp
    tmp="$(mktemp ./.env.XXXXXX)" || { error "Could not create temp file."; return 1; }
    chmod 600 "$tmp"

    cat > "$tmp" <<ENVEOF
# === SXT Validator Dashboard environment ===
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

SXT_LOCAL_VALIDATOR=${SXT_LOCAL_VALIDATOR}
SXT_RPC_URL=${SXT_RPC_URL:-https://rpc.mainnet.sxt.network}
SXT_PROMETHEUS_TARGET=${SXT_PROMETHEUS_TARGET}
NODE_EXPORTER_TARGET=${NODE_EXPORTER_TARGET}
SXT_DATA_MOUNTPOINT=${SXT_DATA_MOUNTPOINT}

SXT_EXPORTER_POLL_INTERVAL=${SXT_EXPORTER_POLL_INTERVAL:-12}
SXT_EXPORTER_PORT=${SXT_EXPORTER_PORT}
SXT_EXPORTER_LOG_LEVEL=${SXT_EXPORTER_LOG_LEVEL:-INFO}
SXT_STAKING_POLL_INTERVAL=${SXT_STAKING_POLL_INTERVAL:-120}
SXT_PRICE_POLL_INTERVAL=${SXT_PRICE_POLL_INTERVAL:-300}

PROMETHEUS_PORT=${PROMETHEUS_PORT}
GRAFANA_PORT=${GRAFANA_PORT}
CLICKHOUSE_HTTP_PORT=${CLICKHOUSE_HTTP_PORT}
CLICKHOUSE_NATIVE_PORT=${CLICKHOUSE_NATIVE_PORT}

COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-sxt-validator-dashboard}
PROMETHEUS_SCRAPE_INTERVAL=${PROMETHEUS_SCRAPE_INTERVAL:-15s}
PROMETHEUS_RETENTION=${PROMETHEUS_RETENTION:-30d}

GRAFANA_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
GRAFANA_BIND=${GRAFANA_BIND}

CLICKHOUSE_USER=sxt_exporter
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
SXT_DASHBOARD_USER=sxt_dashboard
SXT_DASHBOARD_PASSWORD=${SXT_DASHBOARD_PASSWORD}
ENVEOF

    if ! mv "$tmp" .env; then
        error "Could not write .env"
        rm -f "$tmp"
        return 1
    fi
    chmod 600 .env
    return 0
}
